const splashTexts = [
    'the site\'s not done it won\'t be done soon it probably never will be done',
    'i\'m sorry officer but the speed limit does not apply when the guitar solo from free bird by lynyrd skynyrd is playing',
    'it\'s my right to stupidity and i get to use it',
    'that\'s why you built like a 2 for $5 wendy\'s chicken mcnugget sandwich',
    'can you put a cheese stick through a glue gun',
    '2001 chevy highlander',
    'to the town of agua fria rode a stranger one fine day',
    'you may not urinate on the floor but using a 1982 commodore 64 home computer is perfectly acceptable',
    'super paper mario lore',
    'letting the days go by',
    'how do people even be think',
    'by my heel, i care not',
    'how to declare variable in html',
    'nyoom',
    'my money tree died :(',
    'you are a saucy boy',
    'ever heard of the wikipeda getting to philosophy game',
    'carbon fiber stan',
    'if gap, car',
    '(3d printer noises)',
    'i want to become a videogame collectible and just float in midair while spinning',
    'have you heard of the high elves',
    'xkcd is best webcomic',
    'gp2 engine',
    'i should enjoy a mouth watering egg mcmuffin from the new all day breakfast menu only at mcdonald\'s',
    'you have very nice eyes, looks like i\'ll have to take them',
    'shakespeare was a wattpad author',
    'the j stands for jaquayveon tavious',
    'italy',
    'god knew i would be too powerful if i had an attention span',
    'romeo and juliet were killed by an underfunded postal service',
    'don\'t look up the etymology of boba',
    '(source engine ragdoll sounds)',
    'sv_cheats 1',
    'why does twitter',
    'stay awesome',
    'it\'s not "edgy", it\'s comedic nihilism',
    'it\'s turtles all the way down',
    'me when the judge sentences me to death for my crimes against humanity (they were in fact not epic gaming moments)',
    'your honor, my client was simply doing a little trolling',
    'what are these "minecraft random splash texts" you speak of'
]

document.getElementById('splash-text').innerHTML = splashTexts[Math.floor(Math.random() * splashTexts.length)];